project:
  type: website
  resources:
    - "files/AK_CV_full.pdf"
  #output-dir: docs

website:
  title: "Aditya Kher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- href: about.qmd
      #  text: About
      - href: quantum.qmd
        text: Quantum
      - href: defense.qmd
        text: Defense
      - href: cv.qmd
        text: CV

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



