---
title: "Quantum Technology"
---

### Superconducting Device Development
[Transition-edge sensors](https://en.wikipedia.org/wiki/Transition-edge_sensor) are a standard detector technology used in modern astronomy and cosmology instruments, and can also be used as [single-photon detectors](https://en.wikipedia.org/wiki/Single-photon_detector) for quantum information and other domains. A TES is a superconducting [bolometer](https://en.wikipedia.org/wiki/Bolometer) that operates at the edge of the superconducting transition, where its resistance is highly sensitive to changes in temperature. When coupled to an absorber, this makes it an extremely sensitive detector for photons and other particles. Typically, a SQUID ([superconducting quantum interference device](https://en.wikipedia.org/wiki/SQUID)) is used to read out the very small changes in electrical current through the TES that correlate to photon absorption. However, SQUIDs are complex devices, requiring fabrication of multiple layers of superconducting thin films, and they are not straightforward to multiplex. This limits the size of TES arrays, which in turn limits the sensitivity and resolution of instruments that use them.

At Caltech and JPL, I worked under [Prof. Jonas Zmuidzinas](https://www.pma.caltech.edu/people/jonas-zmuidzinas) and [Dr. Peter K. Day](https://www.jpl.nasa.gov/site/research/pday/), who had pioneered a new, easily multiplexable superconducting detector technology called the [microwave kinetic inductance detector](https://en.wikipedia.org/wiki/Microwave_kinetic_inductance_detector). MKIDs are superconducting microwave resonators where the inductance is dominated by [kinetic inductance](https://en.wikipedia.org/wiki/Kinetic_inductance), a property that exists in all conductors but is particularly strong in superconductors. They can be fabricated with a single layer of superconducting material, and are straightforward to multiplex, as resonators in a large array can be designed with slightly different resonant frequencies and all excited and read out via a [frequency comb](https://en.wikipedia.org/wiki/Frequency_comb) on a common feedline.

The group had also been investigating a nonlinearity in the kinetic inductance; namely, that the kinetic inductance has a dependence on the current flowing through the material. For my PhD work, I built on this research and took inspiration from MKID technology in order to develop a novel superconducting current sensor consisting of a microwave resonator with a nonlinear kinetic inductance. This device could be an easily multiplexable alternative to SQUIDs for reading out TESs, which retain some advantages over MKIDs. We named it the kinetic inductance parametric up-converter (KPUP), as it up-converts the low-frequency TES current signal to the microwave domain, where there is much greater available bandwidth for array multiplexing. Like SQUIDs, the added noise from the KPUP, which in principle dissipates no energy, would be quantum-limited.

I designed and simulated KPUP devices and tested them in a dilution refrigerator with a microwave measurement setup. I measured the device response to DC current bias and observed the expected nonlinear kinetic inductance behavior, and then measured the noise referred to the input signal current, meeting performance benchmarks for TES readout. I then integrated the KPUP with a TES and was able to map the superconducting transition of the TES by using the KPUP to read out the current through the TES as I varied its temperature. I also demonstrated operation of a KPUP device as a parametric amplifier by applying a strong microwave pump tone and observing almost 30 dB of microwave gain with near-quantum-limited noise. This has applications for superconducting qubit readout as well as in other domains where low-noise microwave amplification is needed.

This work was presented at several conferences and published in the [Journal of Low Temperature Physics](https://doi.org/10.1007/s10909-015-1364-0). A detailed description of the project can be found in my [PhD thesis](https://resolver.caltech.edu/CaltechTHESIS:02062017-171647432).